### ISSUE TITLE
Issue with token cache

### ISSUE THREAD

**Issue by stefanvangastel** [mayflower/docker-ls#13]
I seem to be having an issue with the token cache when accessing a Docker private registry behind a Gitlab CE installation. At first it works fine after some time it results in 403 responses from the Gitlab OAuth service. If I try a new server to connect from it works again, and after some time it doesnt. 

Seems like the docker-ls is caching a token and not clearing it correctly on token check fail.

**Comment by stefanvangastel** [comment]
I stand corrected.

**Comment by DirtyHairy** [comment]
:smile: For the sake of completeness: `docker-ls` **does** cache tokens issued by the auth server, but the cache is not persistent and only last one invocation. In addition, a new token is requested if the cached token is rejected.
