### ISSUE TITLE
Feature request: repo:tag list

### ISSUE THREAD

**Issue by zoobab** [mayflower/docker-ls#15]
Hi,

I am using docker-ls to list the registry, but I would like to have a feature which is very useful for scripting, which is a list with one repo:tag per line.

I have done it with a shell script around docker-ls in the following form:

```
#!/bin/bash
for repo in `docker-ls repositories -table -level 0 -progress-indicator=false | grep -v REPOSITORY`; do
	TAGS="$(docker-ls tags -progress-indicator=false -json $repo | jq -r '.Tags[]')"
	for tag in `echo $TAGS`; do
		echo $repo:$tag
	done
done
```

Would it be hard to implement?

**Comment by DirtyHairy** [comment]
Hi @zoobab !

Implementing this output format would definitely be possible. However, another way (actually the way I prefer :smile:) for performing such tasks would be to use JSON output together with a JSON processing tool like [jq](https://stedolan.github.io/jq/) --- that's why we added JSON in the first place.

Cheers
-Christian

**Comment by DirtyHairy** [comment]
(never mind the close-reopen, wrong button)

**Comment by zoobab** [comment]
Do you accept shell scripts as PRs?

**Comment by DirtyHairy** [comment]
Sorry, I just saw that you are already using jq to parse the json output. To be honest, I do not want to include shell wrappers into the repo, and I also am reluctant to add support for more specialized output formats. However, what I would be open to would be a kind of configurable output format, maybe using go templates.  Would that be an option for you?

**Comment by zoobab** [comment]
I have published it here:

https://github.com/zoobab/docker-ls/commit/4882a4fa49b2c072ff746a8f17f00fd3073cdf15

**Comment by zoobab** [comment]
Yes, having an output format would be helpful.

**Comment by zoobab** [comment]
Updated the scripts here:

https://github.com/zoobab/docker-ls/tree/master/scripts

**Comment by DirtyHairy** [comment]
Version 0.3.2 Supports golang templates for formatting the output.

**Comment by glensc** [comment]
doc for templates: d371240c3dd46a73f9c516475d5f611c8f699419

**Comment by DirtyHairy** [comment]
Ups :smirk: Seems I forgot to push master. The docs are now included in master, sorry for that!

**Comment by zoobab** [comment]
Do you have any example of a go template for a repo:tag list? Too bad this issue was closed, while the output format is not provided out of the box in the new version.
