### ISSUE TITLE
Feature request: docker-rm an entire repo

### ISSUE THREAD

**Issue by zoobab** [mayflower/docker-ls#16]
Hi,

I am using docker-rm to delete tags, but when I delete all the tags, there is still a repo without tags in there.

Any idea how to delete that repo? Would that be something that docker-rm could do?

Best,

**Comment by DirtyHairy** [comment]
Hi @zoobab !

Unfortunately, this is impossible --- deleting repositories is not supported by the docker registry API.

Cheers
-Christian
