### ISSUE TITLE
Local name servers are not used

### ISSUE THREAD

**Issue by vga101** [mayflower/docker-ls#18]
Hi,
when used with a local private registry, `docker-ls` tries to resolve the host name via Google DNS servers (8.8.8.8) and hence doesn't see locally configured DNS names. Is there a way to not enforce Google DNS and just use the default system-defined name servers?

```
$ docker-ls repositories --registry https://registry.mydomain.org:5000
requesting list . done
ERROR: Get https://registry.mydomain.org:5000/v2/_catalog?n=100: dial tcp: lookup registry.mydomain.org on 8.8.8.8:53: no such host
```

Tested with most recent master branch, commit 3c5e2decd5c671, and installation through Docker.

**Comment by DirtyHairy** [comment]
Hi @vga101 !

Interesting. Are you running on a container? What does `/etc/resolv.conf` look like?

Cheers
-Christian

**Comment by vga101** [comment]
Hi @DirtyHairy,

resolv.conf in the container is:
```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
search mydomain.org

nameserver 8.8.8.8
nameserver 8.8.4.4
```

while on the host system it is:
```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.1.1
search mydomain.org
```

where NetworkManager handles 127.0.1.1 and refers to our local name server IP addresses. 

This does not happen within your docker-ls Dockerfile, but is already present in the golang:latest image: `docker run -it --rm golang:latest cat /etc/resolv.conf` also shows the changed name server. So it's not your fault, just affecting your package... ;-) 

Cheers,
 V

**Comment by vga101** [comment]
Hmm, this name server thing goes all the way back to the official Debian image, which gets populated from a [rootfs.tar.xz archive](https://github.com/tianon/docker-brew-debian/tree/d220bea42308935d3bee1b40701f39e8c0d69860/jessie). There's also some discussion on how to deal with resolv.conf with [Docker](https://github.com/docker/docker/issues/1297) generally. So I guess there's not much you can do and it's rather an issue for the official Debian images.

I'm now quite unhappy now that generally all DNS queries from my containers get handled and monitored by Google... :-(

Anyway, thanks!

**Comment by DirtyHairy** [comment]
I agree, that's a docker issue. Best of luck though :smirk:

**Comment by vga101** [comment]
Just to link the solution here for the record: https://github.com/docker/docker/issues/23910 tells how local DNS servers can be enforced in /etc/docker/daemon.json. Alternatively, setting the DNS servers in /etc/default/docker is possible on Debian/Ubuntu (`DOCKER_OPTS="--dns 172.16.31.201"`).

**Comment by melroy89** [comment]
Example of a `/etc/docker/daemon.json` file:
https://gitlab.melroy.org/snippets/19
