### ISSUE TITLE
Build is failed

### ISSUE THREAD

**Issue by testor321** [mayflower/docker-ls#19]
Hi
Is these any specific prerequisites ? When I run
docker build -t docker-ls .
I get error
Step 5/5 : RUN make clean && make install && cp /go/src/github.com/mayflower/docker-ls/build/bin/* /usr/local/bin/
 ---> Running in 89eec4f7eb7f
rm -fr ./build ./docker-ls.debug
mkdir -p ././build/src/github.com/mayflower/docker-ls
for srcdir in cli lib; \
    do \
        ln -s `pwd`/$srcdir ././build/src/github.com/mayflower/docker-ls/$srcdir; \
    done
if test -n "gopkg.in/yaml.v2 golang.org/x/crypto/ssh/terminal"; then GOPATH=`pwd`/./build go get gopkg.in/yaml.v2 golang.org/x/crypto/ssh/terminal; fi
package gopkg.in/yaml.v2: unrecognized import path "gopkg.in/yaml.v2" (https fetch: Get https://gopkg.in/yaml.v2?go-get=1: dial tcp: i/o timeout)
^Tpackage golang.org/x/crypto/ssh/terminal: unrecognized import path "golang.org/x/crypto/ssh/terminal" (https fetch: Get https://golang.org/x/crypto/ssh/terminal?go-get=1: dial tcp: i/o timeout)
Makefile:67: recipe for target 'build' failed
make: *** [build] Error 1
The command '/bin/sh -c make clean && make install && cp /go/src/github.com/mayflower/docker-ls/build/bin/* /usr/local/bin/' returned a non-zero code: 2

**Comment by DirtyHairy** [comment]
Hi @testor321 !

Looks like there is an issue with your internet connection: `dial tcp: i/o timeout`. Can you check whether you can ping golang.org and gopkg.in?

**Comment by testor321** [comment]
yes, It look OK
ping -c3 golang.org
PING golang.org (172.217.22.177) 56(84) bytes of data.
64 bytes from arn09s11-in-f177.1e100.net (172.217.22.177): icmp_seq=1 ttl=51 time=36.4 ms
64 bytes from arn09s11-in-f177.1e100.net (172.217.22.177): icmp_seq=2 ttl=51 time=36.4 ms
64 bytes from arn09s11-in-f177.1e100.net (172.217.22.177): icmp_seq=3 ttl=51 time=36.4 ms

--- golang.org ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 36.421/36.438/36.460/0.156 ms

ping -c3 gopkg.in
PING gopkg.in (45.33.37.13) 56(84) bytes of data.
64 bytes from li987-13.members.linode.com (45.33.37.13): icmp_seq=1 ttl=40 time=169 ms
64 bytes from li987-13.members.linode.com (45.33.37.13): icmp_seq=2 ttl=40 time=169 ms
64 bytes from li987-13.members.linode.com (45.33.37.13): icmp_seq=3 ttl=40 time=169 ms

--- gopkg.in ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 169.128/169.216/169.267/0.062 ms

**Comment by DirtyHairy** [comment]
Sorry, just saw that you are using the docker build container. It seems that you docker configuration does not permit connections outside the container (I just checked, this works for me).

I'm sorry, but I can't help you there. If you fail to troubleshoot this, you can just build locally or use one of the prebuild [binaries](https://github.com/mayflower/docker-ls/releases).
