### ISSUE TITLE
can docker-rm be used to delete images from a private registry on docker.com?

### ISSUE THREAD

**Issue by JimMcHale** [mayflower/docker-ls#20]
I can list the tag manifest for a particular tag, but when I try to docker-rm the tag I get:
docker-rm  --user myid -p passwd     myid/repo:sha256:c32132207f45c924f1f1aab8b607ca9bbb085896a2f88c86c791cf2b3ef99e8e
invalid API response status 405

Should I be able to delete tags from docker.com? Is there some other way to do this?
tks

**Comment by DirtyHairy** [comment]
Sorry, to the best of my knowledge the docker hub does not support untagging. However, I have not researched this extensively. You might want ask this question on the docker forums --- you'd might get a more qualified answer or even an official statement from docker there.
