### ISSUE TITLE
support official image form

### ISSUE THREAD

**Issue by glensc** [mayflower/docker-ls#26]
https://docs.docker.com/engine/reference/run/#general-form

the form is:
- `IMAGE[:TAG|@DIGEST]`

but this does not work:

```
$ docker-rm ed/gitlab-runner/builds@sha256:82ff0936da09b40393c21cda464312907449aef7069aeebd1ee4fe4938ff2de5
ed/gitlab-runner/builds@sha256:82ff0936da09b40393c21cda464312907449aef7069aeebd1ee4fe4938ff2de5 : no such repository or reference
```

and afaik the tag could be specified too, but it's just ignored,  but visually looking better:

```
ed/gitlab-runner/builds:some_tag@sha256:82ff0936da09b40393c21cda464312907449aef7069aeebd1ee4fe4938ff2de5
```

can't find the blog post right now about that.

**Comment by DirtyHairy** [comment]
Duplicate #5 .
