### ISSUE TITLE
no such repository error from `tags` command

### ISSUE THREAD

**Issue by glensc** [mayflower/docker-ls#27]
using private gitlab server, i get repository from `docker-ls repositories` listing, but querying individual tags tells `no such repository` error:

```
+ docker-ls repositories
advertising/ads-video-converter/test
+ docker-ls tags advertising/ads-video-converter/test
advertising/ads-video-converter/test: no such repository
```

i believe it happens the way gitlab deletes docker images:

```
$ docker pull glen/scratch
$ docker tag glen/scratch registry.gitlab.com/glensc/test-docker-ls/builds:build-1
$ docker push registry.gitlab.com/glensc/test-docker-ls/builds:build-1
```

```
$ docker-ls tags glensc/test-docker-ls/builds
requesting list . done
repository: glensc/test-docker-ls/builds
tags:
- build-1
```

i hit delete for the tag:

![image](https://user-images.githubusercontent.com/199095/43765223-1d48cc34-9a38-11e8-8985-7cd7ea67c25a.png)

-> still ok

i hit delete for the image:

```
$ docker-ls tags glensc/test-docker-ls/builds
requesting list . done
glensc/test-docker-ls/builds: no such repository
````

**Comment by DirtyHairy** [comment]
Yeah, this seems to be connected to deleting all tags from a repository. Can you list tags again once you have pushed a new tag to the empty repository?

**Comment by DirtyHairy** [comment]
Closing for lack of feedback.
