### ISSUE TITLE
Doesn't seem to work with aws ecr registries

### ISSUE THREAD

**Issue by spicysomtam** [mayflower/docker-ls#28]
Get this with ecr registries, and yet skopio can access the registry fine based on credentials in ~/.docker/config.json:
```
$ docker-ls repositories  --registry https://111111111111.dkr.ecr.us-east-1.amazonaws.com
requesting list . done
malformed challenge header: 'Basic realm="https://111111111111.dkr.ecr.us-east-1.amazonaws.com/",service="ecr.amazonaws.com"' Are you shure that you are using the correct (token) auth scheme?

$ docker-ls tags  --registry https://111111111111.dkr.ecr.us-east-1.amazonaws.com myrepo/images
requesting list . done
malformed challenge header: 'Basic realm="https://111111111111.dkr.ecr.us-east-1.amazonaws.com/",service="ecr.amazonaws.com"' Are you shure that you are using the correct (token) auth scheme?

$ skopeo inspect docker://111111111111.dkr.ecr.us-east-1.amazonaws.com/myrepo/image
{
    "Name": "111111111111.dkr.ecr.us-east-1.amazonaws.com/myrepo/image",
    "Digest": "sha256:5340a616e7de2e75f3a18f1bac69abc9605c5ad2e795ed3f06c61de3d12667e6",
```
We can also do this (from aws docs):
```
$ TOKEN=$(aws ecr get-authorization-token --registry-ids 111111111111 --profile foo --region us-east-1 --output text --query authorizationData[].authorizationToken)
$ curl -ns -H "Authorization: Basic $TOKEN" https://111111111111.dkr.ecr.us-east-1.amazonaws.com/v2/_catalog|jq '.'
{
  "repositories": [
    "myrepo/image"
```
Any thoughts, suggestions? Is `docker-ls` still being actively developed, or should we use something else?

**Comment by DirtyHairy** [comment]
Thanks for your feedback. The project is still maintained; I'll have a look at your issue.

**Comment by DirtyHairy** [comment]
Sorry for the delay. It seems that the ECR registry is using basic auth instead of the default token based authentication. However, the documentation you quote suggests that the token is used as basic auth in verbatim, without base64 encoding.

Are you still interested in troubleshooting this issue? If yes, I'll add an experimental option as a possible fix for you to test.

**Comment by GMartinez-Sisti** [comment]
@DirtyHairy I'm having the same behaviour as @spicysomtam .

I'm available to test, if you have the time to create a test branch.

**Comment by stesie** [comment]
agreed that the token based approach doesn't (yet) work ... but for the record, it works using basic authentication like so:

```
$ aws ecr get-login --profile private --region eu-west-1
docker login -u AWS -p PASSWORD -e none https://661571386954.dkr.ecr.eu-west-1.amazonaws.com
```

... take both password and the url from there (actually being a token with a expiration time of about a day currently), then run docker-ls like this:

```
$ docker-ls repositories -r https://661571386954.dkr.ecr.eu-west-1.amazonaws.com --user AWS --password PASSWORD --basic-auth
requesting list . done
repositories:
- testling
```

**Comment by stesie** [comment]
With #7 being fixed, docker-ls now allows to use docker's credential-helpers, especially `docker-credential-ecr-login`.

So given a `.docker/config` like 

```json
{
	"auths": {
		"661571386954.dkr.ecr.eu-west-1.amazonaws.com": {},
		"https://index.docker.io/v1/": {}
	},
	"credsStore": "pass",
	"credHelpers": {
		"661571386954.dkr.ecr.eu-west-1.amazonaws.com": "ecr-login"
	}
}
```

it's now possible to call `docker-ls` like this (mind the `--basic-auth` flag):

```
$ docker-ls repositories -r https://661571386954.dkr.ecr.eu-west-1.amazonaws.com --basic-auth
requesting list . done
repositories:
- testling
```

... which silently invokes the credential helper to get the ecr token itself.
