### ISSUE TITLE
Insecure Registry

### ISSUE THREAD

**Issue by aravind-craft** [mayflower/docker-ls#3]
Hi

Please can you confirm whether this is supported on a insecure registry i.e. without having to pass authentication details?

Thanks

**Comment by DirtyHairy** [comment]
Hi @aravind-murthy!

It is:

```
cnspeckn@cspeckner ~/test $ docker-ls tags --registry https://index.docker.io library/alpine
requesting list . done
repository: library/alpine
tags:
- "2.6"
- "2.7"
- "3.1"
- "3.2"
- "3.3"
- edge
- latest
```

Cheers
  -Christian

**Comment by aravind-craft** [comment]
Hi @DirtyHairy /Christian,

Thank you for the response.

If I may ask, if I need to have image search and image delete features in Docker registry, what is your current recommendation in terms of tools/scripts that I can use?

Obviously I can use docker-ls to list the existing images; Are you aware of any other tools/script which actually delete images (to reclaim disk space) etc - without using the paid DTR of course?

I am currently using registry:v2 but I am not particular about using any specific Docker registry versions as long as it provides me push, pull, search & delete features.

Thank you

**Comment by aravind-craft** [comment]
Also, @DirtyHairy, looking at https://github.com/mayflower/docker-ls/releases - is there a Linux x86_64 version of the precompiled binary available?

**Comment by DirtyHairy** [comment]
Hi @aravind-murthy!

You can use docker-rm (part of docker-ls) to delete tags; however, I don't think the disk space is actually reclaimed. There have recently been garbage collection improvements in docker-distribution though, so this may not be correct anymore. The only other tool capable of admisitrating docker registries that I know from the top of my head is [portus](https://github.com/SUSE/Portus).

As for x86_64: yep, [there is](https://github.com/mayflower/docker-ls/releases/download/v0.1.0/docker-ls-linux-amd64.zip).

Cheers
-Christian

**Comment by aravind-craft** [comment]
@DirtyHairy I forgot to thank you. Thank you.

**Comment by DirtyHairy** [comment]
No worries, you're welcome ;)
