### ISSUE TITLE
Reference is not a content digest

### ISSUE THREAD

**Issue by amittleider** [mayflower/docker-ls#30]
Hi all,

Thanks for the library, it's quite useful. However, I have a problem removing the images from the registry. Here is the command and output:

```
docker run -it docker-ls docker-rm --registry https://[myurl] --user [username] --password [password] walnut-project/walnut/big_nut:94805918c838241ea1d29c434965dc1ea8a2b84613d9748b0da42614703de1c3
invalid request --- make sure that your reference is a content digest
```

I have also tried with the small sha hash, but with the same result. 

Am I doing something wrong or is it a bug?

**Comment by DirtyHairy** [comment]
Removing tags should like fine. However, please make sure that

1. The registry you are working with has support for deleting tags enabled
2. The digest must be prefixed with `sha256`. In your example, that'd be `sha256:94805918c...`
