### ISSUE TITLE
Autocompletion got "bad option: -t" in zsh

### ISSUE THREAD

**Issue by yellowsoar** [mayflower/docker-ls#39]
# Environmentz
macOS 10.15.7 (19H2)
zsh 5.8 (x86_64-apple-darwin19.6.0)
docker-ls version: 0.5.0 (git:0eb4c9a) (go1.15.5 darwin amd64)

# Error message
## docker-ls

```
source <(docker-ls autocomplete bash)
```
stdout:
```
/dev/fd/14:type:795: bad option: -t
```

## docker-rm
```
source <(docker-rm autocomplete bash)
```
stdout
```
/dev/fd/14:type:569: bad option: -t
```

**Comment by stesie** [comment]
I'm confused.  Do you use this with zsh or bash?  Since you take the output of `autocomplete bash` (instead of zsh) and use it with zsh (at least both the version number as well as issue subject tell so) !?

**Comment by yellowsoar** [comment]
@stesie I'm so sorry...
It's my mistake!!!
Long story short.
There's a bug in my rc script for both bash & zsh.
And it leads me to take the wrong args as the current shell.
So, case closed! Thanks!
