### ISSUE TITLE
Authorization issue for tags on GCR

### ISSUE THREAD

**Issue by nyarly** [mayflower/docker-ls#40]
When attempting `docker-ls tags gcr.io/.../...`, on a repository I can push and pull to, I get:

```
requesting list . done
authorization rejected by registry
```

Without verbose output, I'm unclear on how to debug this.

**Comment by DirtyHairy** [comment]
I have released your PR as 0.5.1. Is there anything else to do in this issue, or is it solved?

**Comment by nyarly** [comment]
I was ultimately able to figure out (with the help of debug logging) that the command I wanted looked like

```
docker-ls tags --basic-auth -r https://gcr.io $repo
```

maybe something in the README? Or this comment can stand for docs for the next person. (Me, 2 months from now :) )

**Comment by DirtyHairy** [comment]
> (Me, 2 months from now :) )

😏 That's what documentation is really for. I've added a remark to the readme .
