### ISSUE TITLE
docker-ls return wrong digest value DockerRegistry>2.3

### ISSUE THREAD

**Issue by SRadyukov** [mayflower/docker-ls#6]
Note When deleting a manifest from a registry version 2.3 or later, the following header must be used when HEAD or GET-ing the manifest to obtain the correct digest to delete:

Accept: application/vnd.docker.distribution.manifest.v2+json

**Comment by DirtyHairy** [comment]
Hi @SRadyukov ,

thanks for the pointer to the missing header, I will investigate. Can you supply a testcase (registry version) where the delete indeed fails? I am fairly sure that I have successfully used `docker-rm` in the recent past together with our private 2.3.1 registry.

Cheers
---Christian

**Comment by DirtyHairy** [comment]
658ac78a7f229a5ce94f3419349a3beab6148cec implements support for V2.2 manifests. By default, docker-ls now tries to request a V2.2 manifest by properly setting the `accept` header, fixing this issue.
