### ISSUE TITLE
read auth info from docker config

### ISSUE THREAD

**Issue by rojer** [mayflower/docker-ls#7]
`.dockercfg` and `.docker/config.json` contain registry auth info ("encrypted" with base64)
it would be nice if docker-ls could pull it automatically

**Comment by DirtyHairy** [comment]
Hi @rojer!

Thanks for your input! However, I am not very enthusiastic about consuming another programs config files as changes to the format lie outside my control. In addition, I detest the idea of storing plaintext passwords within a config file, and I don't want to adopt that bad habit :smirk:

Cheer
    -Christian

**Comment by rojer** [comment]
i am with you, totally.
however, in this case this is a closely related program, namely docker, so keeping up to date with it is kinda in scope.
and second - it's docker that does the reprehensible thing of storing the credentials, we're not increasing the level of evil :)

credentials for authentication with registry are stored in docker config. it is a bad idea to store them in plain text, but that's what docker does, so we might as well use it.
this would make docker-ls really convenient to use.

for example, i use throw-away passwords for docker registry, i don't know it. to use docker-ls i actually had to retrieve it from the config myself. i'd like docker-ls to do it - or at least attempt.

**Comment by DirtyHairy** [comment]
Gauging from the number of thumbs up, I stand overruled 😈  I'm currently in the progress of redoing the CLI with cobra / viper and will include this as an option (after the initial release of 0.3.0) :smirk:

**Comment by harobed** [comment]
Some news about this issue?
